# Distant horizons
[flavor_groups.dh]
name = "Distant Horizons"
side = "client"
choices = ["dh_on", "dh_off"]

[metafile.distanthorizons]
flavors = "dh_on"

[flavor_groups.iris]
name = "Iris"
side = "client"
choices = [
  { id = "iris_shaders", name = "Iris & Shaders" },
  { id = "iris_on", name = "Iris only" },
  { id = "iris_off", name = "None" },
]

# Iris
[metafile.colorwheel]
flavors = "iris_on"
[metafile.colorwheel-patcher]
flavors = "iris_on"
[metafile.iris]
flavors = "iris_on"

# Shaders
[metafile.bliss-shader]
flavors = "iris_shaders"
[metafile.bsl-shaders]
flavors = "iris_shaders"
[metafile.complementary-reimagined]
flavors = "iris_shaders"
[metafile.complementary-unbound]
flavors = "iris_shaders"
[metafile.insanity-shader]
flavors = "iris_shaders"
[metafile.nostalgia-shader]
flavors = "iris_shaders"
[metafile.solas-shader]
flavors = "iris_shaders"

# Particular
[flavor_groups.particular]
name = "Particular"
side = "client"
choices = ["particular_on", "particular_off"]

[metafile.particular-reforged]
flavors = "particular_on"

# Visuality
[flavor_groups.visuality]
name = "Visuality"
side = "client"
choices = ["visuality_on", "visuality_off"]

[metafile.visuality-forge]
flavors = "visuality_on"

# Dynlights
[flavor_groups.dynamic]
name = "Dynamic Lights"
side = "client"
choices = ["dynamic_on", "dynamic_off"]

[metafile.sodium-dynamic-lights]
flavors = "dynamic_on"
[metafile.create-dynamic-lights]
flavors = "dynamic_on"
